{
 "title": "Plex BMO",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  { "title": "Activity", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Heartbeat",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "plex_up{instance=\"smolboi\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Health",
   "type": "state-timeline",
   "gridPos": { "h": 3, "w": 21, "x": 3, "y": 1 },
   "targets": [
    {
     "expr": "plex_up{instance=\"smolboi\"}",
     "legendFormat": "Heartbeat"
    }
   ]
  },
  {
   "title": "Activity",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(plex_video_transcode_sessions_count{state!=\"paused\", instance=\"smolboi\"})",
     "legendFormat": "Transcodes"
    },
    {
     "expr": "sum(plex_sessions_count{state!=\"paused\", instance=\"smolboi\"})",
     "legendFormat": "Streams"
    },
    {
     "expr": "sum(plex_media_downloads_count{instance=\"smolboi\"}) > 0",
     "legendFormat": "Downloads"
    }
   ]
  },
  { "title": "Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(netdata_system_cpu_percentage_average{dimension!=\"idle\", instance=\"smolboi\"})",
     "legendFormat": "usage"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "((node_memory_MemTotal_bytes{instance=\"smolboi\"} - node_memory_MemAvailable_bytes{instance=\"smolboi\"}) / node_memory_MemTotal_bytes{instance=\"smolboi\"}) * 100",
     "legendFormat": "usage"
    }
   ]
  },
  {
   "title": "Network",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "Kbits" } },
   "targets": [
    {
     "expr": "sum by (dimension) (netdata_net_net_kilobits_persec_average{instance=\"smolboi\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "iGPU",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg(netdata_intelgpu_engine_busy_perc_percentage_average{instance=\"smolboi\"})",
     "legendFormat": "usage"
    }
   ]
  },
  { "title": "Library", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Movies",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 35 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "plex_media_count{title=\"Movies\", instance=\"smolboi\"}",
     "legendFormat": "{{ title }}"
    }
   ]
  },
  {
   "title": "TV Shows",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 35 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "plex_media_count{title=\"TV Shows\", instance=\"smolboi\"}",
     "legendFormat": "{{ title }}"
    }
   ]
  },
  {
   "title": "TV Shows - Episodes",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 35 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "plex_media_count{title=\"TV Shows - Episodes\", instance=\"smolboi\"}",
     "legendFormat": "{{ title }}"
    }
   ]
  },
  {
   "title": "Daily Library Movements",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "targets": [
    {
     "expr": "delta(plex_media_count{instance=\"smolboi\"}[1d] offset 1d)",
     "legendFormat": "{{ title }}"
    }
   ]
  },
  { "title": "Downloads", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "Downloads",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 44 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(plex_media_downloads_count{instance=\"smolboi\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Download Durations",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 21, "x": 3, "y": 44 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(sum_over_time(plex_media_downloads_count{instance=\"smolboi\"}[$__range]) > 0)",
     "legendFormat": "{{ username }}"
    }
   ]
  }
 ]
}